server:
  port: 8081
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    bean: jasyptEncryptor


---
spring:
  profile:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/marketdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: dev
    password: dev

signkey:
  data-go: Qa6NXZbhyBRWdsfOjUSXTcZJOL985MbhfomZLiye%2Bk1lkE2DvP2pMrSLdmvwjTRr0%2BWOIQOLvecxJkqc%2FAXRZA%3D%3D

---
spring:
  profile:
    active: real
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/marketdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: dev
    password: dev

signkey:
  data-go: Qa6NXZbhyBRWdsfOjUSXTcZJOL985MbhfomZLiye%2Bk1lkE2DvP2pMrSLdmvwjTRr0%2BWOIQOLvecxJkqc%2FAXRZA%3D%3D

---