server:
  port: 9080
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: info

---
spring:
  profile:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.104:3306/stock_db
    username: ENC(RqxpbaGRs7/Jnf5+Xh6oYA==)
    password: ENC(XAnd/Zk8AoW/b0ynx0ovog==)

signkey:
  data-go: UbBresjb6IVpoH2VpdxNeuC0YB8dAr5FQqncYrbSW3XhE3igo5WKraPa5aGHAAHchpnaMbr%2F5gHrKyryz%2FoipQ%3D%3D
  dart: c207c7fb3fa4aecf7e9012257b17012b5949dff8

file:
  path: /Users/kada/data/dart/


cron:
  krx:
    daily-info: 0 0 14 * * 1-6

logging:
  level:
    com:
      stock:
        quant: debug

---
spring:
  profile:
    active: prod
  jpa:
    show-sql: false

  datasource:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ooooo
    password: oooo0
    hikari:
      maximum-pool-size: 10

signkey:
  data-go: UbBresjb6IVpoH2VpdxNeuC0YB8dAr5FQqncYrbSW3XhE3igo5WKraPa5aGHAAHchpnaMbr%2F5gHrKyryz%2FoipQ%3D%3D
  dart: c207c7fb3fa4aecf7e9012257b17012b5949dff8

file:
  path: /Users/kada/data/dart/

cron:
  krx:
    daily-info: 0 0 14 * * 1-6

logging:
  level:
    root: info
---