server:
  port: 9080
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/db_stock
    username: remote
    password: remote1234
    hikari:
      maximum-pool-size: 50
    transaction:
      default-timeout: 10


signkey:
  data-go: UbBresjb6IVpoH2VpdxNeuC0YB8dAr5FQqncYrbSW3XhE3igo5WKraPa5aGHAAHchpnaMbr%2F5gHrKyryz%2FoipQ%3D%3D
  dart: c207c7fb3fa4aecf7e9012257b17012b5949dff8

file:
  path: /Users/kada/data/dart/


cron:
  krx:
    daily-info: 0 0 14 * * 1-6

logging:
  level:
    com:
      stock:
        quant: debug

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username: ooooo
    password: ooooo
    hikari:
      maximum-pool-size: 10

signkey:
  data-go: UbBresjb6IVpoH2VpdxNeuC0YB8dAr5FQqncYrbSW3XhE3igo5WKraPa5aGHAAHchpnaMbr%2F5gHrKyryz%2FoipQ%3D%3D
  dart: c207c7fb3fa4aecf7e9012257b17012b5949dff8

file:
  path: /Users/kada/data/dart/

cron:
  krx:
    daily-info: 0 0 14 * * 1-6

logging:
  level:
    root: info
---