server:
  port: 8081
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor


---
spring:
  profile:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/marketdb
    username: ENC(FSVuRfXSpoTzMPZUpTQpVA==)
    password: ENC(IfHjdyjoBjaczvj0jbgoKQ==)

signkey:
  data-go: Qa6NXZbhyBRWdsfOjUSXTcZJOL985MbhfomZLiye%2Bk1lkE2DvP2pMrSLdmvwjTRr0%2BWOIQOLvecxJkqc%2FAXRZA%3D%3D
  dart: c207c7fb3fa4aecf7e9012257b17012b5949dff8

---
spring:
  profile:
    active: prod
  jpa:
    show-sql: false

  datasource:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    username: dev
    password: dev
    hikari:
      maximum-pool-size: 10

signkey:
  data-go: Qa6NXZbhyBRWdsfOjUSXTcZJOL985MbhfomZLiye%2Bk1lkE2DvP2pMrSLdmvwjTRr0%2BWOIQOLvecxJkqc%2FAXRZA%3D%3D

---