jasypt:
  encryptor:
    bean: jasyptStringEncryptor


server:
  port: 9180
  error:
    whitelabel:
      enabled: false

batch:
  job:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    defer-datasource-initialization : true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/db_stock;MODE=MySQL;AUTO_SERVER=TRUE
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
      #mysql의 경우 다음 설정을 추가
      data-source-properties:
        rewriteBatchedStatements: true

  sql:
    init:
      mode: never

signkey:
  path : /data/pass.json

file:
  path: /data/dart/

cron:
  krx:
    daily-info: 0 0 14 * * 1-6
    month-info: 0 0 15 1 * *

quant:
  allow-ip: 0:0:0:0:0:0:0:1,127.0.0.1
  boosting: 11,12,1,2,3,4

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/db_stock
    username: remote
    password: remote1234
    hikari:
      maximum-pool-size: 100
    transaction:
      default-timeout: 10
  sql:
    init:
      mode: never

signkey:
  path : /data/pass.json


file:
  path: /data/dart/

cron:
  krx:
    daily-info: 0 0 14 * * 1-6
    month-info: 0 0 15 1 * *

quant:
  allow-ip: 0:0:0:0:0:0:0:1
  boosting: 11,12,1,2,3,4

---