
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: info

server:
  port: 9180
  error:
    whitelabel:
      enabled: false

batch:
  job:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/db_stock;MODE=MySQL;
    username: sa
    password:
    hikari:
      maximum-pool-size: 50
  sql:
    init:
      mode: never

signkey:
  data-go: UbBresjb6IVpoH2VpdxNeuC0YB8dAr5FQqncYrbSW3XhE3igo5WKraPa5aGHAAHchpnaMbr%2F5gHrKyryz%2FoipQ%3D%3D
  dart: c207c7fb3fa4aecf7e9012257b17012b5949dff8

file:
  path: /data/dart/

cron:
  krx:
    daily-info: 0 0 14 * * 1-6
    month-info: 0 0 15 1 * *

quant:
  allow-ip: 0:0:0:0:0:0:0:1,127.0.0.1
  boosting: 11,12,1,2,3,4


---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/db_stock
    username: remote
    password: remote1234
    hikari:
      maximum-pool-size: 50
    transaction:
      default-timeout: 10
  sql:
    init:
      mode: never

signkey:
  data-go: UbBresjb6IVpoH2VpdxNeuC0YB8dAr5FQqncYrbSW3XhE3igo5WKraPa5aGHAAHchpnaMbr%2F5gHrKyryz%2FoipQ%3D%3D
  dart: c207c7fb3fa4aecf7e9012257b17012b5949dff8

file:
  path: /data/dart/

cron:
  krx:
    daily-info: 0 0 14 * * 1-6
    month-info: 0 0 15 1 * *

quant:
  allow-ip: 0:0:0:0:0:0:0:1
  boosting: 11,12,1,2,3,4
---