server:
  port: 9180
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: local

    month-info: 0 0 15 1 * *

logging:
  level:
    com:
      stock:
        quant: debug



---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false



logging:
  level:
    root: info


---