
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/db_quant_batch
    username: sa
    password:
    hikari:
      maximum-pool-size: 50

  sql:
    init:
      mode: always

  batch:
    job:
      enabled: false

cron:
  krx:
    daily-info: 0 0 14 * * 1-6
    month-info: 0 0 15 1 * *

logging:
  level:
    com:
      stock:
        quant: debug



---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/db_quant_batch
    username: remote
    password: remote1234
    hikari:
      maximum-pool-size: 50
    transaction:
      default-timeout: 10

  batch:
    job:
      enabled: false

cron:
  krx:
    daily-info: 0 0 14 * * 1-6

logging:
  level:
    root: info

async:
  core-pool-size: 10
  max-pool-size: 10000
  queue-capacity: 100000
  thread-name-prefix: STOCK-SERVICES-
---